services:
  vault:
    image: vault:1.11.3
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  init:
    image: vault:1.11.3
    container_name: init
    environment:
      - VAULT_ADDR=http://vault:8200
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./init.sh:/usr/local/bin/init.sh
      - data:/vault/file/
    command: /usr/local/bin/init.sh
    restart: on-failure
    depends_on:
      - vault

volumes:
  data: